(global-set-key (kbd "s-{") 'tab-bar-switch-to-prev-tab)
(global-set-key (kbd "s-}") 'tab-bar-switch-to-next-tab)
(global-set-key (kbd "s-t") 'tab-bar-new-tab)
(global-set-key (kbd "s-w") 'tab-bar-close-tab)
(setq tab-bar-select-tab-modifiers "super")
(global-set-key (kbd "C-c l g g") 'xref-find-definitions)
(global-set-key (kbd "C-c l g r") 'xref-find-references)
